import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of service — Doc Batch Generator',
  description: 'The terms that apply when you use Doc Batch Generator.',
};

const sections: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'Accepting the terms',
    paragraphs: [
      'By creating an account or using Doc Batch Generator, you agree to these terms. If you do not agree, please do not use the service.',
    ],
  },
  {
    heading: 'Your content',
    paragraphs: [
      'You keep ownership of the sample files you upload, the instructions you write, and the documents the service generates for you. You are responsible for having the right to upload the sample content you provide. Community members can access only documents explicitly shared with their community and the messages posted there.',
    ],
  },
  {
    heading: 'Acceptable use',
    paragraphs: [
      'Do not use the service to create or upload content that is illegal, fraudulent, or infringes someone else\u2019s rights, and do not attempt to access other accounts\u2019 data, overload the service, or circumvent usage limits. Accounts that abuse the service may be suspended.',
    ],
  },
  {
    heading: 'AI-generated output',
    paragraphs: [
      'Documents are generated by AI and may contain mistakes. Review generated content before relying on it. The service does not guarantee that output is accurate, complete, or fit for any particular purpose.',
    ],
  },
  {
    heading: 'Availability and limits',
    paragraphs: [
      'Basic access costs KES 200 per month and includes up to 25 generated documents and 5 sample uploads per calendar month. Advanced costs KES 900 per month and includes up to 50 generated documents, 15 sample uploads, and a five-person community for sharing documents and chat. Plan access is manually activated by an administrator after payment confirmation. The app does not process payments. Monthly limits reset on the first day of the UTC calendar month.',
    ],
  },
  {
    heading: 'No warranty',
    paragraphs: [
      'The service is provided \u201cas is\u201d without warranties of any kind, to the fullest extent permitted by law. We are not liable for damages arising from your use of the service or the content you generate with it.',
    ],
  },
  {
    heading: 'Changes to the terms',
    paragraphs: [
      'These terms may be updated from time to time. Continued use of the service after changes are published constitutes acceptance of the updated terms.',
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-2xl px-4 py-14">
      <h1 className="text-3xl font-semibold tracking-tight text-ink">
        Terms of service
      </h1>
      <p className="mt-2 text-sm text-faint">Last updated: October 2026</p>

      <div className="mt-10 space-y-9">
        {sections.map((s) => (
          <section key={s.heading}>
            <h2 className="text-xl font-medium text-ink">{s.heading}</h2>
            {s.paragraphs.map((p, i) => (
              <p
                key={i}
                className="mt-3 text-[15px] leading-relaxed text-mute"
              >
                {p}
              </p>
            ))}
          </section>
        ))}
      </div>
    </div>
  );
}
